export type Project = {
  slug: string;
  name: string;
  tagline: string;
  url: string;
  org: "Navana Group" | "Prothom Alo" | "Personal";
  role: string;
  stack: string[];
  featured?: boolean;
};

export const projects: Project[] = [
  {
    slug: "navana",
    name: "Navana Group",
    tagline: "Corporate site for one of Bangladesh's largest conglomerates.",
    url: "https://navana.com",
    org: "Navana Group",
    role: "Tech Lead — architecture, build, infra",
    stack: ["Next.js", "Node.js", "MySQL", "MariaDB", "PostgreSQL", "AlmaLinux", "Apache"],
    featured: true,
  },
  {
    slug: "navana-real-estate",
    name: "Navana Real Estate",
    tagline: "Property portfolio and project showcase.",
    url: "https://navanarealestate.com",
    org: "Navana Group",
    role: "Tech Lead",
    stack: ["Next.js", "Node.js", "MySQL", "MariaDB", "PostgreSQL"],
    featured: true,
  },
  {
    slug: "gloria-jeans-bd",
    name: "Gloria Jean's Coffees BD",
    tagline: "Bangladesh franchise site for the global coffee brand.",
    url: "https://gloriajeans.com.bd",
    org: "Navana Group",
    role: "Tech Lead",
    stack: ["Next.js", "Tailwind", "MySQL", "MariaDB", "PostgreSQL"],
    featured: true,
  },
  {
    slug: "la-tarte-bd",
    name: "La Tarte BD",
    tagline: "Premium patisserie brand site.",
    url: "https://latarte.com.bd",
    org: "Navana Group",
    role: "Tech Lead",
    stack: ["Next.js", "Tailwind", "MySQL", "MariaDB", "PostgreSQL"],
  },
  {
    slug: "navana-logistics",
    name: "Navana Logistics",
    tagline: "End-to-end logistics solutions for Bangladesh.",
    url: "https://navanalogistics.com",
    org: "Navana Group",
    role: "Tech Lead",
    stack: ["Next.js", "MySQL", "MariaDB", "PostgreSQL"],
  },
  {
    slug: "navana-furniture",
    name: "Navana Furniture",
    tagline: "Furniture catalog and brand presence.",
    url: "https://navanafurniture.com",
    org: "Navana Group",
    role: "Tech Lead",
    stack: ["Next.js", "NestJS", "Prisma", "PostgreSQL"],
  },
  {
    slug: "navana-cng",
    name: "Navana CNG",
    tagline: "CNG conversion and refueling services site.",
    url: "https://navanacng.com",
    org: "Navana Group",
    role: "Tech Lead",
    stack: ["Next.js", "MySQL", "MariaDB", "PostgreSQL"],
  },
  {
    slug: "navana-engineering",
    name: "Navana Engineering",
    tagline: "Engineering services brand site.",
    url: "https://navanaengineering.com",
    org: "Navana Group",
    role: "Tech Lead",
    stack: ["Next.js", "MySQL", "MariaDB", "PostgreSQL"],
  },
  {
    slug: "prothom-alo",
    name: "Prothom Alo",
    tagline: "Bangladesh's largest newspaper — 6.6M+ daily readers.",
    url: "https://www.prothomalo.com",
    org: "Prothom Alo",
    role: "Web Developer (2021–2025)",
    stack: ["React", "Next.js", "Quintype/Bold", "Malibu", "PostgreSQL", "Redis", "Elasticsearch", "Cloudflare"],
    featured: true,
  },
  {
    slug: "kishor-alo",
    name: "Kishor Alo",
    tagline: "Children's & teens magazine — flagship of Prothom Alo's youth media.",
    url: "https://www.kishoralo.com",
    org: "Prothom Alo",
    role: "Web Developer (2021–2025)",
    stack: ["React", "Next.js", "Quintype/Bold", "Malibu", "Cloudflare"],
    featured: true,
  },
  {
    slug: "biggan-chinta",
    name: "Biggan Chinta",
    tagline: "Bangladesh's leading popular-science magazine.",
    url: "https://www.bigganchinta.com",
    org: "Prothom Alo",
    role: "Web Developer (2021–2025)",
    stack: ["React", "Next.js", "Quintype/Bold", "Malibu", "Cloudflare"],
    featured: true,
  },
  {
    slug: "bondhushava",
    name: "Bondhushava",
    tagline: "Community platform & friendship-circle magazine of Prothom Alo.",
    url: "https://www.bondhushava.com",
    org: "Prothom Alo",
    role: "Web Developer (2021–2025)",
    stack: ["React", "Next.js", "Quintype/Bold", "Malibu", "Cloudflare"],
    featured: true,
  },
  {
    slug: "prothom-alo-epaper",
    name: "Prothom Alo ePaper",
    tagline: "Digital replica edition of the printed daily newspaper.",
    url: "https://epaper.prothomalo.com",
    org: "Prothom Alo",
    role: "Web Developer (2021–2025)",
    stack: ["React", "Next.js", "Node.js", "Cloudflare"],
  },
  {
    slug: "prothom-alo-trust",
    name: "Prothom Alo Trust",
    tagline: "Humanitarian arm of Prothom Alo — campaigns and relief programs.",
    url: "https://trust.prothomalo.com",
    org: "Prothom Alo",
    role: "Web Developer (2021–2025)",
    stack: ["React", "Next.js", "Quintype/Bold", "Cloudflare"],
  },
  {
    slug: "nagorik-songbad",
    name: "Nagorik Songbad",
    tagline: "Citizen journalism platform powered by Prothom Alo.",
    url: "https://nagorik.prothomalo.com",
    org: "Prothom Alo",
    role: "Web Developer (2021–2025)",
    stack: ["React", "Next.js", "Quintype/Bold", "Cloudflare"],
  },
  {
    slug: "chironton-71",
    name: "Chironton 71",
    tagline: "1971 Liberation War archive and resource hub.",
    url: "https://1971.prothomalo.com",
    org: "Prothom Alo",
    role: "Web Developer (2021–2025)",
    stack: ["React", "Next.js", "Quintype/Bold", "Cloudflare"],
  },
];
